# Generated as the initial schema for SprintForge.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="Project",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=120)),("slug",models.SlugField(max_length=140,unique=True)),("description",models.TextField(blank=True)),("owner",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="owned_projects",to=settings.AUTH_USER_MODEL))],options={"indexes":[models.Index(fields=["owner","slug"],name="project_owner_slug_idx")]}),
        migrations.CreateModel(name="Sprint",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=120)),("goal",models.TextField(blank=True)),("start_date",models.DateField(blank=True,null=True)),("end_date",models.DateField(blank=True,null=True)),("active",models.BooleanField(default=False)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="sprints",to="core.project"))]),
        migrations.CreateModel(name="Membership",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("role",models.CharField(choices=[("OWNER","Owner"),("ADMIN","Admin"),("MEMBER","Member"),("VIEWER","Viewer")],default="MEMBER",max_length=10)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="memberships",to="core.project")),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="project_memberships",to=settings.AUTH_USER_MODEL))],options={"indexes":[models.Index(fields=["user","project"],name="membership_user_project_idx")]}),
        migrations.CreateModel(name="Task",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("title",models.CharField(max_length=240)),("type",models.CharField(choices=[("TASK","Task"),("ISSUE","Issue"),("BUG","Bug")],default="TASK",max_length=10)),("description",models.TextField(blank=True)),("status",models.CharField(choices=[("BACKLOG","Backlog"),("TODO","To do"),("IN_PROGRESS","In progress"),("DONE","Done")],default="BACKLOG",max_length=16)),("priority",models.CharField(choices=[("LOW","Low"),("MEDIUM","Medium"),("HIGH","High"),("CRITICAL","Critical")],default="MEDIUM",max_length=10)),("position",models.PositiveIntegerField(default=0)),("version",models.PositiveIntegerField(default=1)),("due_date",models.DateField(blank=True,null=True)),("assignee",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="assigned_tasks",to=settings.AUTH_USER_MODEL)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="tasks",to="core.project")),("reporter",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="reported_tasks",to=settings.AUTH_USER_MODEL)),("sprint",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="tasks",to="core.sprint"))],options={"ordering":["status","position","created_at"],"indexes":[models.Index(fields=["project","status"],name="task_project_status_idx"),models.Index(fields=["project","assignee"],name="task_project_assignee_idx")]}),
        migrations.CreateModel(name="Comment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("body",models.TextField(max_length=5000)),("author",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),("task",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="comments",to="core.task"))]),
        migrations.CreateModel(name="TaskAttachment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("file",models.FileField(upload_to="task_attachments/%Y/%m/%d")),("original_name",models.CharField(max_length=255)),("size",models.PositiveBigIntegerField()),("task",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="attachments",to="core.task")),("uploaded_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Activity",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("verb",models.CharField(max_length=80)),("metadata",models.JSONField(default=dict)),("actor",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="activities",to="core.project")),("task",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="core.task"))]),
        migrations.CreateModel(name="Notification",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("message",models.CharField(max_length=255)),("read_at",models.DateTimeField(blank=True,null=True)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="core.project")),("recipient",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name="membership",constraint=models.UniqueConstraint(fields=("project","user"),name="unique_project_member")),
        migrations.AddConstraint(model_name="sprint",constraint=models.UniqueConstraint(condition=models.Q(("active",True)),fields=("project",),name="one_active_sprint_per_project")),
        migrations.AddConstraint(model_name="task",constraint=models.UniqueConstraint(fields=("project","status","position"),name="unique_task_position")),
    ]
